import type { ParkingCardData } from './types'

export const mockParkingCards: ParkingCardData[] = [
    {
        id: 1,
        name: '중앙로 공영 이륜차 주차장',
        address: '서울시 중구 중앙로 12',
        latitude: 37.56647,
        longitude: 126.97796,
        distanceMeters: 120,
        thumbnailUrl: null,
        source: 'public',
        isFree: true,
        operatingHours: '24시간',
        hasRoof: true,
        likeCount: 24,
        dislikeCount: 2,
        lastVerifiedAt: '2026-09-12T10:30:00',
        reviewCount: 8,
    },
    {
        id: 2,
        name: '행복빌딩 뒤편 공터',
        address: '서울시 중구 세종대로 18길 7',
        latitude: 37.56712,
        longitude: 126.97682,
        distanceMeters: 240,
        thumbnailUrl: null,
        source: 'user',
        isFree: true,
        operatingHours: null,
        hasRoof: false,
        likeCount: 8,
        dislikeCount: 1,
        lastVerifiedAt: '2026-09-14T07:00:00',
        reviewCount: 3,
    },
    {
        id: 3,
        name: '서울역 환승센터 이륜차존',
        address: '서울시 용산구 한강대로 405',
        latitude: 37.55468,
        longitude: 126.97067,
        distanceMeters: 350,
        thumbnailUrl: null,
        source: 'public',
        isFree: false,
        operatingHours: '06:00-24:00',
        hasRoof: true,
        likeCount: 56,
        dislikeCount: 3,
        lastVerifiedAt: '2026-09-13T14:20:00',
        reviewCount: 14,
    },
    {
        id: 4,
        name: '카페거리 골목 공간',
        address: '서울시 중구 퇴계로 24길 9',
        latitude: 37.56193,
        longitude: 126.98641,
        distanceMeters: 410,
        thumbnailUrl: null,
        source: 'user',
        isFree: true,
        operatingHours: '24시간',
        hasRoof: false,
        likeCount: 12,
        dislikeCount: 0,
        lastVerifiedAt: '2026-09-11T18:10:00',
        reviewCount: 5,
    },
    {
        id: 5,
        name: '구청 공영주차장 이륜차구역',
        address: '서울시 중구 창경궁로 17',
        latitude: 37.56409,
        longitude: 126.99754,
        distanceMeters: 560,
        thumbnailUrl: null,
        source: 'public',
        isFree: true,
        operatingHours: '09:00-18:00',
        hasRoof: true,
        likeCount: 33,
        dislikeCount: 1,
        lastVerifiedAt: '2026-09-14T06:30:00',
        reviewCount: 9,
    },
]
