import type { ParkingDetailData } from './types'

const defaultParkingImages = [
    '/images/default-parking.png',
    '/images/default-parking.png',
    '/images/default-parking.png',
]

export const mockParkingDetails: ParkingDetailData[] = [
    {
        id: 1,
        name: '중앙로 공영 이륜차 주차장',
        address: '서울시 중구 중앙로 12',
        type: '공영',
        isFree: true,
        hasRoof: true,
        operatingHours: '24시간',
        capacity: 15,
        feeDescription: null,
        description: '인도 침범 없이 지정 구역 내에만 주차 가능합니다.',
        imageUrls: defaultParkingImages,
        lastConfirmedAt: '2026-09-12T10:30:00',
        recommendCount: 24,
        notRecommendCount: 3,
        reviewCount: 8,
        updatedAt: '2026-09-12T10:30:00',
        isFavorite: false,
    },
    {
        id: 2,
        name: '행복빌딩 뒤편 공터',
        address: '서울시 중구 세종대로 18길 7',
        type: '제보',
        isFree: true,
        hasRoof: false,
        operatingHours: null,
        capacity: null,
        feeDescription: null,
        description: '건물 뒤편에 마련된 이륜차 주차 가능 공간입니다.',
        imageUrls: defaultParkingImages,
        lastConfirmedAt: '2026-09-14T07:00:00',
        recommendCount: 8,
        notRecommendCount: 2,
        reviewCount: 3,
        updatedAt: '2026-09-14T07:00:00',
        isFavorite: false,
    },
    {
        id: 3,
        name: '서울역 환승센터 이륜차존',
        address: '서울시 용산구 한강대로 405',
        type: '공영',
        isFree: false,
        hasRoof: true,
        operatingHours: '06:00-24:00',
        capacity: 30,
        feeDescription: '기본 30분 1,000원, 이후 10분당 300원',
        description: '환승센터 이용객을 위한 지정 이륜차 주차 구역입니다.',
        imageUrls: defaultParkingImages,
        lastConfirmedAt: '2026-09-13T14:20:00',
        recommendCount: 56,
        notRecommendCount: 5,
        reviewCount: 14,
        updatedAt: '2026-09-13T14:20:00',
        isFavorite: false,
    },
    {
        id: 4,
        name: '카페거리 골목 공간',
        address: '서울시 중구 퇴계로 24길 9',
        type: '제보',
        isFree: true,
        hasRoof: false,
        operatingHours: '24시간',
        capacity: 5,
        feeDescription: null,
        description: '통행을 방해하지 않도록 골목 안쪽 표시 구역을 이용해 주세요.',
        imageUrls: defaultParkingImages,
        lastConfirmedAt: '2026-09-11T18:10:00',
        recommendCount: 12,
        notRecommendCount: 1,
        reviewCount: 5,
        updatedAt: '2026-09-11T18:10:00',
        isFavorite: false,
    },
    {
        id: 5,
        name: '구청 공영주차장 이륜차구역',
        address: '서울시 중구 창경궁로 17',
        type: '공영',
        isFree: true,
        hasRoof: true,
        operatingHours: '09:00-18:00',
        capacity: 20,
        feeDescription: null,
        description: '구청 운영시간 동안 이용할 수 있는 공영 이륜차 주차 구역입니다.',
        imageUrls: defaultParkingImages,
        lastConfirmedAt: '2026-09-14T06:30:00',
        recommendCount: 33,
        notRecommendCount: 4,
        reviewCount: 9,
        updatedAt: '2026-09-14T06:30:00',
        isFavorite: false,
    },
]
